In [114]:
from __future__ import print_function, division
import pandas as pd
import numpy as np
# if needed: pip install requests or conda install requests
import requests
from bs4 import BeautifulSoup
requests.__path__

['/Users/kelvin/anaconda3/lib/python3.7/site-packages/requests']

In [5]:
#HIV by country
url = 'https://apps.who.int/gho/athena/data/GHO/HIV_0000000001,HIV_0000000009,HIV_ARTCOVERAGE.html?profile=ztable&filter=REGION:*;COUNTRY:-'
response = requests.get(url)
page = response.text

In [115]:
soup = BeautifulSoup(page, "html.parser")

In [116]:
article_values = [entry.text for entry in soup.find_all('td')]

In [126]:
#column_names = list_data[0]
#column_names
columns = ["GHO", "PUBLISH_STATE", "YEAR", "REGION", "DISPLAY_VALUE", "NUMERIC_VALUE", "LOW_RANGE", "HIGH_RANGE", "COMMENT"]

In [118]:
from collections import defaultdict

article_dict = defaultdict(list)

for idx, article_value in enumerate(article_values):
    if idx % 9 == 0:
        article_dict[columns[0]].append(article_value)
        article_dict[columns[1]].append(article_values[idx+1])
        article_dict[columns[2]].append(article_values[idx+2])
        article_dict[columns[3]].append(article_values[idx+3])
        article_dict[columns[4]].append(article_values[idx+4])
        article_dict[columns[5]].append(article_values[idx+5])
        article_dict[columns[6]].append(article_values[idx+6])
        article_dict[columns[7]].append(article_values[idx+7])

In [119]:
article_dict.keys()

dict_keys(['GHO', 'PUBLISH_STATE', 'YEAR', 'REGION', 'DISPLAY_VALUE', 'NUMERIC_VALUE', 'LOW_RANGE', 'HIGH_RANGE'])

In [120]:
data_hiv = pd.DataFrame(article_dict)

In [121]:
data_hiv.columns = data_hiv.columns.str.lower()
data_hiv.columns

Index(['gho', 'publish_state', 'year', 'region', 'display_value',
       'numeric_value', 'low_range', 'high_range'],
      dtype='object')

In [122]:
data_hiv = data_hiv[['gho', 'year', 'region',
       'numeric_value', 'low_range', 'high_range']]

In [123]:
data_hiv

,gho,year,region,numeric_value,low_range,high_range
0,Estimated number of people (all ages) living w...,2018,Africa,25700000.00000,22200000.00000,29500000.00000
1,Reported number of people receiving antiretrov...,2018,Americas,2368000.00000,2084000.00000,2463000.00000
2,Estimated antiretroviral therapy coverage amon...,2018,Europe,55.00000,43.00000,64.00000
3,Reported number of people receiving antiretrov...,2018,Europe,1404000.00000,1236000.00000,1460000.00000
4,Estimated number of people (all ages) living w...,2018,Western Pacific,1900000.00000,1700000.00000,2100000.00000
5,Reported number of people receiving antiretrov...,2018,(WHO) Global,23331000.00000,20531000.00000,24264000.00000
6,Reported number of people receiving antiretrov...,2018,Africa,16331000.00000,14371000.00000,16984000.00000
7,Estimated antiretroviral therapy coverage amon...,2018,Americas,67.00000,49.00000,82.00000
8,Estimated number of people (all ages) living w...,2018,Europe,2500000.00000,2300000.00000,2800000.00000
9,Estimated antiretroviral therapy coverage amon...,2018,South-East Asia,53.00000,39.00000,71.00000
10,Reported number of people receiving antiretrov...,2018,Western Pacific,1109000.00000,976000.00000,1154000.00000
11,Estimated antiretroviral therapy coverage amon...,2018,(WHO) Global,62.00000,47.00000,74.00000
12,Estimated number of people (all ages) living w...,2018,Americas,3500000.00000,3000000.00000,4200000.00000
13,Estimated antiretroviral therapy coverage amon...,2018,Eastern Mediterranean,21.00000,13.00000,31.00000
14,Reported number of people receiving antiretrov...,2018,Eastern Mediterranean,82800.00000,72900.00000,86200.00000
15,Estimated number of people (all ages) living w...,2018,South-East Asia,3800000.00000,3100000.00000,4900000.00000
16,Estimated number of people (all ages) living w...,2018,(WHO) Global,37900000.00000,32700000.00000,44000000.00000
17,Estimated antiretroviral therapy coverage amon...,2018,Africa,64.00000,48.00000,76.00000
18,Estimated number of people (all ages) living w...,2018,Eastern Mediterranean,400000.00000,290000.00000,570000.00000
19,Reported number of people receiving antiretrov...,2018,South-East Asia,2036000.00000,1791000.00000,2117000.00000
20,Estimated antiretroviral therapy coverage amon...,2018,Western Pacific,59.00000,47.00000,69.00000

In [124]:
pd.get_dummies(data_hiv["gho"]).head()

,Estimated antiretroviral therapy coverage among people living with HIV (%),Estimated number of people (all ages) living with HIV,Reported number of people receiving antiretroviral therapy
0,0,1,0
1,0,0,1
2,1,0,0
3,0,0,1
4,0,1,0

In [125]:
pd.get_dummies(data_hiv["region"]).head()

,(WHO) Global,Africa,Americas,Eastern Mediterranean,Europe,South-East Asia,Western Pacific
0,0,1,0,0,0,0,0
1,0,0,1,0,0,0,0
2,0,0,0,0,1,0,0
3,0,0,0,0,1,0,0
4,0,0,0,0,0,0,1